import streamlit as st
import pandas as pd
import json

from utils.file_parser   import parse_file, format_file_size
from utils.type_inference import infer_all_column_types, is_problematic
from utils.data_cleaner   import apply_cleaning_rules, build_default_rules
from utils.ai_client      import analyze_structure

#  Page config 
st.set_page_config(
    page_title="DataRefine",
    page_icon="🔬",
    layout="wide",
    initial_sidebar_state="expanded",
)

# Custom CSS 
st.markdown("""
<style>
  @import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500;600&family=IBM+Plex+Sans:wght@400;500;600&display=swap');

  html, body, [class*="css"] { font-family: 'IBM Plex Sans', sans-serif; }
  code, .stCode, pre, .dataframe { font-family: 'IBM Plex Mono', monospace !important; }

  /* Section headers */
  .section-label {
    font-family: 'IBM Plex Mono', monospace;
    font-size: 10px;
    font-weight: 600;
    letter-spacing: 2px;
    text-transform: uppercase;
    color: #555;
    margin-bottom: 6px;
  }

  /* Badges */
  .badge {
    display: inline-block;
    padding: 2px 8px;
    border-radius: 99px;
    font-family: 'IBM Plex Mono', monospace;
    font-size: 11px;
    font-weight: 500;
    margin-right: 4px;
  }
  .badge-date    { background: #0d2240; color: #4a9eff; }
  .badge-integer,.badge-float { background: #0a2412; color: #22c55e; }
  .badge-text    { background: #1e1e1e; color: #888; }
  .badge-list    { background: #1f0d2a; color: #a78bfa; }
  .badge-mixed   { background: #2a1e08; color: #f59e0b; }
  .badge-empty   { background: #1c0d0d; color: #ef4444; }
  .badge-boolean { background: #0d1e2a; color: #38bdf8; }

  /* Log entry */
  .log-entry {
    padding: 4px 0;
    font-family: 'IBM Plex Mono', monospace;
    font-size: 12px;
    border-bottom: 1px solid #1a1a1a;
    display: flex;
    gap: 10px;
    align-items: baseline;
  }
  .log-success { color: #22c55e; }
  .log-warning { color: #f59e0b; }
  .log-error   { color: #ef4444; }
  .log-info    { color: #4a9eff; }

  /* Metric override for export section */
  .export-metric .stMetricValue {
    font-size: 28px !important;
    color: #22c55e !important;
  }

  /* Rule item */
  .rule-tag {
    font-family: 'IBM Plex Mono', monospace;
    font-size: 10px;
    color: #555;
    background: #1a1a1a;
    padding: 1px 6px;
    border-radius: 4px;
    margin-left: 6px;
  }

  /* Hide default Streamlit footer */
  footer { visibility: hidden; }
</style>
""", unsafe_allow_html=True)


# Session state init 
_DEFAULTS = {
    "raw_df":          None,
    "file_info":       None,
    "analysis_result": None,
    "rules":           [],
    "cleaned_result":  None,
    "transform_log":   [],
}
for _k, _v in _DEFAULTS.items():
    if _k not in st.session_state:
        st.session_state[_k] = _v


#  Helpers 

def highlight_issues(val) -> str:
    """Pandas Styler function — amber background for problematic cells."""
    return "background-color: #2a1e08; color: #f59e0b;" if is_problematic(str(val)) else ""


def highlight_changes(df: pd.DataFrame, changes: dict) -> pd.DataFrame:
    """Returns a same-shaped DataFrame of CSS strings for changed cells."""
    styles = pd.DataFrame("", index=df.index, columns=df.columns)
    for (row_label, col) in changes:
        if row_label in styles.index and col in styles.columns:
            styles.at[row_label, col] = "background-color: #2a1e08; color: #f59e0b;"
    return styles


def build_log_markdown(log: list, df: pd.DataFrame, total_changed: int) -> str:
    icons = {"success": "✅", "warning": "⚠️", "error": "❌", "info": "ℹ️"}
    lines = [
        "# DataRefine — Transformation Log",
        "",
        f"**Date:** {pd.Timestamp.now().strftime('%Y-%m-%d')}",
        f"**Output:** {len(df)} rows × {len(df.columns)} columns",
        f"**Total cells cleaned:** {total_changed}",
        "",
        "## Changes Applied",
        "",
    ]
    for entry in log:
        icon = icons.get(entry["level"], "•")
        lines.append(f"- {icon} **{entry['col']}** → {entry['msg']} ({entry['count']} affected)")
    lines += ["", "---", "*Generated by DataRefine*"]
    return "\n".join(lines)


def reset_state():
    for k, v in _DEFAULTS.items():
        st.session_state[k] = v if not isinstance(v, list) else []
    for key in list(st.session_state.keys()):
        if key.startswith("rule_") or key == "diff_toggle":
            del st.session_state[key]


# Sidebar 
with st.sidebar:
    st.markdown("## 🔬 DataRefine")
    st.markdown("*Intelligent data cleaning for messy files*")
    st.divider()

    api_key = st.text_input(
        "AI API Key",
        type="password",
        placeholder="Paste your API key…",
        help="Your API key — stored in session memory only, never saved or shared.",
    )
    if api_key:
        if len(api_key) > 20:
            st.success("Key set ✓")
        else:
            st.warning("Check key format")
    else:
        st.caption("Required for AI analysis. Optional for default rules.")

    if st.session_state.file_info:
        info = st.session_state.file_info
        st.divider()
        st.markdown(f"**{info['name']}**")
        c1, c2 = st.columns(2)
        c1.metric("Rows", f"{info['rows']:,}")
        c2.metric("Cols", info["cols"])
        st.caption(format_file_size(info["size"]))
        st.divider()
        if st.button("🔄 Reset / New file", use_container_width=True):
            reset_state()
            st.rerun()

    st.divider()
    st.markdown(
        "<span style='font-size:11px; color:#555;'>Rahil Dobariya · DataRefine</span>",
        unsafe_allow_html=True,
    )


#  Header
st.markdown("# DataRefine")
st.markdown(
    "Upload any messy Excel or CSV — AI analyzes structure, flags issues, "
    "and cleans everything up. Every change is logged so you see exactly what happened."
)
st.divider()



#  SECTION 01 — UPLOAD

st.markdown('<div class="section-label">01 — Upload</div>', unsafe_allow_html=True)

uploaded = st.file_uploader(
    "Drop your file here",
    type=["csv", "xls", "xlsx"],
    label_visibility="collapsed",
    help="Supports .csv, .xls, .xlsx — any messy real-world data",
)

if uploaded is not None and st.session_state.raw_df is None:
    with st.spinner("Parsing file…"):
        try:
            df, info = parse_file(uploaded)
            st.session_state.raw_df    = df
            st.session_state.file_info = info
            st.session_state.rules     = build_default_rules(df)
        except Exception as e:
            st.error(f"Could not parse file: {e}")
    st.rerun()

if st.session_state.raw_df is None:
    st.info("👆 Upload a .csv, .xls, or .xlsx file to get started. Try `examples/messy_sample.csv`.")
    st.stop()



#  SECTION 02 — RAW DATA PREVIEW 

st.divider()
st.markdown('<div class="section-label">02 — Raw Data Preview</div>', unsafe_allow_html=True)

raw_df    = st.session_state.raw_df
col_types = infer_all_column_types(raw_df)

# Summary badges
badge_html = ""
for col, ct in col_types.items():
    t = ct["type"]
    badge_html += f'<span class="badge badge-{t}">{col} [{t}]</span>'

issue_count = sum(
    1 for col in raw_df.columns
    for val in raw_df[col]
    if is_problematic(str(val))
)

m1, m2, m3 = st.columns(3)
m1.metric("Total Rows",    f"{len(raw_df):,}")
m2.metric("Columns",        len(raw_df.columns))
m3.metric("Likely Issues",  f"~{issue_count:,}", delta_color="inverse")

# Styled preview (first 20 rows)
preview = raw_df.head(20)
try:
    styled_raw = preview.style.map(highlight_issues)
    st.dataframe(styled_raw, use_container_width=True, height=320)
except Exception:
    st.dataframe(preview, use_container_width=True, height=320)

st.caption(
    f"First 20 of {len(raw_df):,} rows shown · "
    "**Amber cells** = likely data quality issue"
)

# Column type legend
st.markdown(badge_html, unsafe_allow_html=True)



#  SECTION 03 — AI ANALYSIS

st.divider()
st.markdown('<div class="section-label">03 — AI Analysis</div>', unsafe_allow_html=True)

btn_col, hint_col = st.columns([2, 8])

with btn_col:
    analyze_clicked = st.button(
        "✦ Analyze with AI",
        disabled=not api_key,
        use_container_width=True,
        help="Sends first 15 rows to the AI — no other data leaves your machine.",
    )

with hint_col:
    if not api_key:
        st.info("Enter your API key in the sidebar to enable AI analysis.")
    elif not st.session_state.analysis_result:
        st.caption("AI will detect format, map columns, flag issues, and propose transformation rules.")

if analyze_clicked and api_key:
    with st.spinner("AI is reading your data…"):
        try:
            result = analyze_structure(api_key, raw_df)

            ai_rules = [
                {**r, "enabled": r.get("enabled", True)}
                for r in result.get("rules", [])
            ]
            # Supplement with any default rules the AI didn't cover
            ai_type_col = {f"{r['type']}:{r.get('column', '')}" for r in ai_rules}
            default_rules = build_default_rules(raw_df)
            extras = [
                r for r in default_rules
                if f"{r['type']}:{r.get('column', '')}" not in ai_type_col
            ]

            st.session_state.analysis_result = result
            st.session_state.rules = ai_rules + extras

            # Reset rule checkbox states so they initialize from new rules
            for key in list(st.session_state.keys()):
                if key.startswith("rule_"):
                    del st.session_state[key]

        except Exception as e:
            st.error(f"AI analysis failed: {e}")
    st.rerun()

#  Show analysis results 
if st.session_state.analysis_result:
    result = st.session_state.analysis_result

    fmt = result.get("row_format", "single")
    fmt_badge = {"single": "🔵 Single-row records", "paired": "🟣 Paired-row records",
                 "multi-header": "🟡 Multi-header"}.get(fmt, fmt)
    st.markdown(f"**Detected format:** `{fmt_badge}`")

    col_left, col_right = st.columns(2)

    with col_left:
        st.markdown("**Column Map**")
        cm = result.get("column_map", [])
        if cm:
            cm_df = pd.DataFrame(cm)
            # Keep only columns that exist
            available = [c for c in ["index", "raw_name", "semantic", "type"] if c in cm_df.columns]
            st.dataframe(cm_df[available], use_container_width=True, hide_index=True, height=240)
        else:
            st.caption("No column map returned.")

    with col_right:
        st.markdown("**Detected Issues**")
        issues = result.get("issues", [])
        if issues:
            issues_df = pd.DataFrame(issues)
            st.dataframe(issues_df, use_container_width=True, hide_index=True, height=240)
        else:
            st.success("No significant issues detected.")

st.markdown("")

#  Transformation rules checklist 
rules = st.session_state.rules

if rules:
    enabled_count = sum(1 for r in rules if r.get("enabled"))
    st.markdown(f"**Transformation Rules** — {enabled_count}/{len(rules)} enabled")

    ca, cb, _ = st.columns([1, 1, 10])
    if ca.button("Enable all",  key="btn_en_all"):
        for r in rules: r["enabled"] = True
        for k in list(st.session_state.keys()):
            if k.startswith("rule_"): del st.session_state[k]
        st.rerun()
    if cb.button("Disable all", key="btn_dis_all"):
        for r in rules: r["enabled"] = False
        for k in list(st.session_state.keys()):
            if k.startswith("rule_"): del st.session_state[k]
        st.rerun()

    for i, rule in enumerate(rules):
        rule_key = f"rule_{rule['id']}"
        if rule_key not in st.session_state:
            st.session_state[rule_key] = rule.get("enabled", True)

        col_suffix = f"  [{rule['column']}]" if rule.get("column") else ""
        label = f"{rule['label']}{col_suffix}"

        checked = st.checkbox(label, key=rule_key)
        rules[i]["enabled"] = checked
else:
    st.caption("No rules available yet. Upload a file first.")

#  Apply button
st.markdown("")
apply_col, skip_col = st.columns([2, 8])

with apply_col:
    apply_clicked = st.button(
        "▶ Apply Cleaning",
        type="primary",
        use_container_width=True,
        disabled=not rules,
    )

with skip_col:
    if not st.session_state.analysis_result:
        st.caption("Skipping AI? Click **Apply Cleaning** to use the default heuristic rules above.")

if apply_clicked and rules:
    progress_placeholder = st.empty()
    prog_bar = progress_placeholder.progress(0, text="Starting…")

    def on_progress(pct: int):
        prog_bar.progress(pct / 100, text=f"Cleaning rows… {pct}%")

    try:
        result = apply_cleaning_rules(raw_df, rules, on_progress)
        progress_placeholder.empty()
        st.session_state.cleaned_result = result
        st.session_state.transform_log  = result["log"]
    except Exception as e:
        progress_placeholder.empty()
        st.error(f"Cleaning failed: {e}")
        st.stop()

    st.rerun()


#  SECTION 04 — TRANSFORMATION LOG
if st.session_state.transform_log:
    st.divider()
    st.markdown('<div class="section-label">04 — Transformation Log</div>', unsafe_allow_html=True)

    total_changed = (
        st.session_state.cleaned_result.get("total_changed", 0)
        if st.session_state.cleaned_result else 0
    )

    level_icon = {"success": "🟢", "warning": "🟡", "error": "🔴", "info": "🔵"}

    log_html = '<div style="background:#111;border:1px solid #222;border-radius:6px;padding:12px;max-height:240px;overflow-y:auto;font-family:\'IBM Plex Mono\',monospace;font-size:12px;">'
    for entry in st.session_state.transform_log:
        icon  = level_icon.get(entry["level"], "⚪")
        col_s = f'<span style="color:#4a9eff;">{entry["col"]}</span>' if not entry["col"].startswith("(") else f'<span style="color:#555;">{entry["col"]}</span>'
        log_html += (
            f'<div style="padding:3px 0;border-bottom:1px solid #1a1a1a;">'
            f'{icon} {col_s} '
            f'<span style="color:#888;">→ {entry["msg"]}</span> '
            f'<span style="color:#444;margin-left:auto;">({entry["count"]:,})</span>'
            f'</div>'
        )
    log_html += "</div>"
    st.markdown(log_html, unsafe_allow_html=True)

    if total_changed > 0:
        unique_cols = len({e["col"] for e in st.session_state.transform_log
                           if not e["col"].startswith("(")})
        st.success(f"✓ {total_changed:,} cells cleaned across {unique_cols} columns")


#  SECTION 05 — CLEAN DATA PREVIEW
if st.session_state.cleaned_result:
    st.divider()
    st.markdown('<div class="section-label">05 — Clean Data Preview</div>', unsafe_allow_html=True)

    clean_result = st.session_state.cleaned_result
    clean_df     = clean_result["df"]
    changes      = clean_result["changes"]

    show_changed = st.checkbox("Show changed rows only", key="diff_toggle")

    if show_changed:
        changed_row_labels = {rl for (rl, _) in changes}
        display_df = clean_df.loc[
            [lb for lb in clean_df.index if lb in changed_row_labels][:100]
        ]
        st.caption(f"Showing {len(display_df)} changed rows (first 100 max)")
    else:
        display_df = clean_df.head(20)
        st.caption(f"First 20 of {len(clean_df):,} rows · **Amber** = modified cell")

    try:
        # Subset changes to the displayed rows
        display_changes = {
            (rl, col): True
            for (rl, col) in changes
            if rl in display_df.index
        }
        styled_clean = display_df.style.apply(
            lambda df: highlight_changes(df, display_changes), axis=None
        )
        st.dataframe(styled_clean, use_container_width=True, height=320)
    except Exception:
        st.dataframe(display_df, use_container_width=True, height=320)

    # Updated column types after cleaning
    clean_types = infer_all_column_types(clean_df)
    type_html = "".join(
        f'<span class="badge badge-{ct["type"]}">{col} [{ct["type"]} {int(ct["confidence"]*100)}%]</span>'
        for col, ct in clean_types.items()
    )
    st.markdown(type_html, unsafe_allow_html=True)



#  SECTION 06 — EXPORT
if st.session_state.cleaned_result:
    st.divider()
    st.markdown('<div class="section-label">06 — Export</div>', unsafe_allow_html=True)

    clean_result  = st.session_state.cleaned_result
    clean_df      = clean_result["df"]
    total_changed = clean_result["total_changed"]

    csv_bytes = clean_df.to_csv(index=False).encode("utf-8")
    orig_name = st.session_state.file_info.get("name", "data")
    base_name = orig_name.rsplit(".", 1)[0]
    out_name  = f"{base_name}_clean.csv"

    # Summary metrics
    e1, e2, e3, e4 = st.columns(4)
    e1.metric("Rows Exported",   f"{len(clean_df):,}")
    e2.metric("Columns",          len(clean_df.columns))
    e3.metric("File Size",        format_file_size(len(csv_bytes)))
    e4.metric("Cells Cleaned",   f"{total_changed:,}")

    st.markdown("")

    dl_col, log_col = st.columns(2)

    with dl_col:
        st.download_button(
            label=f"↓  Download  {out_name}",
            data=csv_bytes,
            file_name=out_name,
            mime="text/csv",
            use_container_width=True,
            type="primary",
        )

    with log_col:
        log_md = build_log_markdown(
            st.session_state.transform_log, clean_df, total_changed
        )
        st.download_button(
            label="📋  Download transformation log (.md)",
            data=log_md.encode("utf-8"),
            file_name=f"{base_name}_transform_log.md",
            mime="text/markdown",
            use_container_width=True,
        )
